// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  sidebar: [
    {
      type: 'category',
      label: 'Expériences',
      items: ['Experiences/stage-appli-sourcing']
    },
    {
      type: 'category',
      label: 'Compétences',
      items: ['Competences/C1-realiser-developpement-application', 'Competences/C2-optimiser-application', 'Competences/C3-administrer-systeme-communiquant', 'Competences/C4-optimiser-bdd-interagir-securite', 'Competences/C5-conduire-projet', 'Competences/C6-collaborer-equipe']
    },
    {
      type: 'category',
      label: 'Exemples',
      items: ['Exemples/feat-colonne-PJs', 'Exemples/feat-archivage-multiple', 'Exemples/feat-staffing', 'Exemples/refacto-rmc-plume', 'Exemples/organisation-jira']
    }
  ],
};

export default sidebars;
